apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: otel
  labels:
    app: opentelemetry
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      probabilistic_sampler:
        sampling_percentage: 20
      batch:
        send_batch_max_size: 1000
        send_batch_size: 100
        timeout: 10s

    connectors:
      datadog/connector:
    exporters:
      debug:
        verbosity: detailed
      datadog:
        api:
          site: ap1.datadoghq.com
          key: ${env:DD_API_KEY}


    service:
      pipelines:
        logs:
          receivers: [otlp]
          processors: []
          exporters: [datadog]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [datadog/connector]
        traces/sampling:
          receivers: [datadog/connector]
          processors: []
          exporters: [debug,datadog]